resource-pack:
  enabled: true
  url: "https://junerhobart.github.io/blume/blume-pack.zip"
  sha1: "68133ab95542a91968f1c23525470f769ab18633"
  required: false
  prompt: "<green>Blume</green> uses a resource pack for custom items. Please accept."
