name: Blume
version: '${project.version}'
main: io.blume.BlumePlugin
bootstrapper: io.blume.enchants.BlumeBootstrap
api-version: '26.2'
description: a QOL focused plugin suite.
authors:
  - junerhobart
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    Geyser-Spigot:
      load: BEFORE
      required: false

permissions:
  blume.admin:
    description: Blume admin commands
    default: op
  blume.vouch:
    description: Un-graylist players
    default: op
  blume.verified:
    description: Verified player - not graylisted
    default: op
